name: readr_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# iOS and android is the same version
# dev version
version: 4.2.0+69
# prod version
# version: 4.1.2+354

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # http ajax call
  http: ^0.13.3
  # launching a URL in the mobile platform
  url_launcher: ^6.0.4
  # blocs and cubits.
  flutter_bloc: ^7.1.0
  # toast Library for Flutter
  fluttertoast: ^8.0.8
  # webview
  webview_flutter: ^2.1.1
  # mirrormedia embedded code
  flutter_embedded_webview: 
    git:
      url: git://github.com/mirror-media/flutter_embedded_webview.git
      ref: master
      version: ^0.2.0
  # local storage
  localstorage: ^4.0.0+1
  # A Flutter plugin to store data in secure storage
  flutter_secure_storage: ^3.3.5
  # drag and drop object
  reorderables: ^0.3.2
  # automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^3.0.0
  # cached network image
  cached_network_image: ^3.0.0
  # share url
  share: ^2.0.4
  # A Flutter widget that scrolls text infinitely.
  marquee: ^1.5.2
  # carousel slider in flutter
  carousel_slider: ^4.0.0
  # widget from html
  flutter_widget_from_html: ^0.6.1
  # video player
  video_player: ^2.1.4
  # a friendly Material or Cupertino UI for video
  chewie: ^1.2.0
  # audio service
  audioplayers: ^0.19.1
  # spin
  flutter_spinkit: ^5.1.0
  # flutter cache manager
  flutter_cache_manager: ^3.1.2
  # package for working with MIME type definitions
  mime: ^1.0.0
  # app link
  uni_links: ^0.5.1
  # mirrormedia constants
  constants: 
    git:
      url: git://github.com/mirror-media/constants.git
      ref: master
      version: ^2.0.0
  
  # force app to upgrade
  upgrader: ^3.3.1
  # android in app update
  in_app_update: ^1.1.13
  # get package info 
  package_info_plus: ^1.3.0
  # display ios 14+ tracking authorization dialog and request permission to collect data.
  app_tracking_transparency: ^2.0.2+1
  # version class
  version: ^2.0.0
  
  # firebase
  firebase_core: ^1.7.0
  # firebase analytics API
  firebase_analytics: ^9.0.3
  # firebase messaging
  firebase_messaging: ^10.0.8
  # firebase remote config
  firebase_remote_config: ^0.11.0+2
  # firebase ad mob
  google_mobile_ads:
    git:
      url: https://github.com/SuaMusica/googleads-mobile-flutter.git
      path: packages/google_mobile_ads
      ref: feature/suamusica
  # firebase dynamic links 
  firebase_dynamic_links: ^2.0.7

  # firebase auth
  firebase_auth: ^3.1.3
  # google sign in
  google_sign_in: ^5.1.1
  # facebook sign in
  flutter_facebook_auth: ^3.5.2
  # apple sign in
  sign_in_with_apple: ^3.2.0

  # a storefront-independent API for purchases in Flutter apps.
  in_app_purchase: ^2.0.1

  # generate app icons
  flutter_launcher_icons: ^0.9.0

  intl: ^0.17.0

dependency_overrides:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # generate splash screen
  flutter_native_splash: ^1.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/icon.jpg
    - assets/image/facebook_icon.png
    - assets/image/google_icon.png
    - assets/image/apple_icon.png
    - assets/image/wine_warning.png
    - assets/image/ig_icon.png
    - assets/image/line_icon.png
    - assets/image/yt_icon.png
    - packages/constants/countries.json
    - packages/constants/taiwan-districts.json
    - assets/data/records.json
    - assets/data/menu.json
    - assets/data/defaultNotificationList.json
    # section ad data
    - assets/data/iOSTestSectionAd.json
    - assets/data/iOSDevSectionAd.json   
    - assets/data/iOSSectionAd.json
    - assets/data/androidTestSectionAd.json
    - assets/data/androidDevSectionAd.json
    - assets/data/androidSectionAd.json
    # story ad data
    - assets/data/iOSTestStoryAd.json
    - assets/data/iOSDevStoryAd.json
    - assets/data/iOSStoryAd.json
    - assets/data/androidTestStoryAd.json
    - assets/data/androidDevStoryAd.json
    - assets/data/androidStoryAd.json
    # magazine image
    - assets/image/magazine/magazineDownloadIcon.png
    - assets/image/magazine/hami.png
    - assets/image/magazine/kono.png
    - assets/image/magazine/my_book.png
    - assets/image/magazine/pubu.png
    - assets/image/magazine/readmoo.png
    # member subscription
    - assets/image/badge.png
    - assets/image/subscription_icon.png
    - assets/image/subscribe_banner_mobile.jpg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
